### ISSUE TITLE
AssertionError: action space does not inherit from `gym.spaces.Space`, actual type: <class 'list'>

### ISSUE THREAD

**Issue by mylad13** [yang-xy20/async_mappo#2]
When running the train_gridworld.sh script I get a bunch of errors for different ForkServerProcess numbers about the action space.
Do you know what I need to change to fix this?
For extra context, i tried to use wandb but I got permission errors, so I added the argument --use_wandb to set it to false.

Error example:
Process ForkServerProcess-29:
Traceback (most recent call last):
  File "/home/farjadnm/miniconda3/envs/mazelab/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/farjadnm/miniconda3/envs/mazelab/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/farjadnm/async_mappo/onpolicy/envs/env_wrappers.py", line 411, in infoworker
    env = env_fn_wrapper.x()
  File "train/train_gridworld.py", line 21, in init_env
    env = GridWorldEnv(all_args)
  File "/home/farjadnm/async_mappo/onpolicy/envs/gridworld/GridWorld_Env.py", line 46, in __init__
    self.env = gym.make(self.scenario_name)
  File "/home/farjadnm/miniconda3/envs/mazelab/lib/python3.7/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/farjadnm/miniconda3/envs/mazelab/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 23, in __init__
    check_action_space(env.action_space)
  File "/home/farjadnm/miniconda3/envs/mazelab/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 75, in check_space
    f"{space_type} space does not inherit from `gym.spaces.Space`, actual type: {type(space)}"
AssertionError: action space does not inherit from `gym.spaces.Space`, actual type: <class 'list'>

**Comment by mylad13** [comment]
I solved this by changing the file passive_env_checker.py to not check for the action space type, and proceeded to train the model.
